# Generated by Django 4.1.7 on 2023-03-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_alter_book_img'),
        ('users', '0009_alter_tempuser_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(null=True)),
                ('place', models.CharField(max_length=255, verbose_name='Место встречи')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetings.meeting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='particepents',
            field=models.ManyToManyField(blank=True, through='meetings.MeetingToUser', to='users.myuser'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='temp_users',
            field=models.ManyToManyField(blank=True, to='users.tempuser'),
        ),
    ]
