# Generated by Django 4.1.7 on 2023-03-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(null=True)),
                ('place', models.CharField(max_length=255, verbose_name='Место встречи')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetings.meeting')),
            ],
        ),
    ]
