# Generated by Django 4.1.7 on 2023-02-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tempuser'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='temp_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tempuser'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='particepents',
            field=models.ManyToManyField(through='meetings.MeetingToUser', to='users.myuser'),
        ),
        migrations.AlterField(
            model_name='meetingtouser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.myuser'),
        ),
    ]
