# Generated by Django 4.1.7 on 2023-03-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtouser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.myuser'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='particepents',
            field=models.ManyToManyField(blank=True, through='meetings.MeetingToUser', to='users.myuser'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='temp_users',
            field=models.ManyToManyField(blank=True, to='users.tempuser'),
        ),
    ]
