# Generated by Django 4.1.7 on 2023-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tempuser'),
        ('meetings', '0002_meeting_temp_users_alter_meeting_particepents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='temp_users',
        ),
        migrations.AddField(
            model_name='meeting',
            name='temp_users',
            field=models.ManyToManyField(blank=True, to='users.tempuser'),
        ),
    ]
