# Generated by Django 4.1.7 on 2023-03-13 13:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telegram',
            field=models.CharField(blank=True, help_text='Ваш правильный ник в телерам, если он есть', max_length=255, validators=[users.models.UnicodeTelegramValidator()]),
        ),
    ]
