# Generated by Django 4.1.7 on 2023-03-14 07:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='telegram',
            field=models.CharField(help_text='Ваш правильный ник в телерам, если он есть', max_length=255, validators=[users.models.UnicodeTelegramValidator()]),
        ),
    ]
