# Generated by Django 4.1.6 on 2023-02-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, verbose_name='telegram'),
        ),
    ]
