# Generated by Django 4.1.6 on 2023-02-22 12:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telegram',
            field=models.CharField(blank=True, help_text='Обязательное поле. Начинается с @', max_length=255, validators=[users.models.UnicodeTelegramValidator()]),
        ),
    ]
