# Generated by Django 4.1.7 on 2023-03-23 13:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tempuser_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/avatars'), upload_to='avatars/%Y-%m-%d'),
        ),
    ]
