# Generated by Django 4.1.7 on 2023-02-28 08:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(help_text='Обязательное поле. Начинается с @', max_length=255, validators=[users.models.UnicodeTelegramValidator()])),
            ],
        ),
    ]
