# Generated by Django 4.1.7 on 2023-03-01 12:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tempuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='telegram',
            field=models.CharField(help_text='Обязательное поле. Начинается с @', max_length=255, unique=True, validators=[users.models.UnicodeTelegramValidator()]),
        ),
    ]
