# Generated by Django 4.1.7 on 2023-03-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_tempuser_email_alter_tempuser_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
