# Generated by Django 4.1.7 on 2023-03-01 13:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_tempuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='telegram',
            field=models.CharField(help_text='Обязательное поле. Начинается с @', max_length=255, validators=[users.models.UnicodeTelegramValidator()]),
        ),
    ]
