# Generated by Django 4.1.7 on 2023-03-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
