# Generated by Django 4.1.7 on 2023-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('img', models.ImageField(blank=True, upload_to='books/%Y-%m-%d/', verbose_name='Обложка')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('google_img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
