# Generated by Django 4.1.7 on 2023-03-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_google_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
